# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:12.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  civiform:
    image: civiform
    restart: always
    container_name: play
    links:
      - "db:database"
    ports:
      - 9000:9000
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_S3_REGION
      - AWS_S3_BUCKET_NAME
      - IDCS_CLIENT_ID
      - IDCS_SECRET
      - ADFS_CLIENT_ID
      - ADFS_SECRET
    build: .
    volumes:
      - ./universal-application-tool-0.0.1:/usr/src/universal-application-tool-0.0.1
    command: ~run
