# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  uat:
    image: uat
    restart: always
    container_name: play
    #links:
    #  - "db:database"
    ports:
      - 9000:9000
    build: 
      context: .
      dockerfile: docker/Dockerfile_uat
    volumes:
      - ./universal-application-tool-0.0.1:/usr/src/universal-application-tool-0.0.1
    command: sbt ~run
